
["Feature Toggles"]
	"Basins Wear" = true
	#includes all engines, tfmg and steam
	"Engines Wear" = true
	"Distillation Outputs Wear" = true
	"Waterwheels Wear" = true
	"Windmills Wear" = true
	"Basins Can Be Upgraded" = true

["Lifetimes (how many ticks blocks run/can be used before breaking)"]
	#For basins
	"Basin Lifetime" = 25000.0
	#For regular/radial/turbine engines
	"Small Engine Lifetime" = 20000.0
	#For large engines
	"Large Engine Lifetime" = 20000.0
	#For simple large engines
	"Simple Large Engine Lifetime" = 17000.0
	#For steam engines
	"Steam Engine Lifetime" = 20000.0
	#For distillation outputs
	"Distillation Output Lifetime" = 20000.0
	#For water wheels
	"Waterwheel Lifetime" = 17000.0
	#For windmill bearings
	"Windmill Lifetime" = 25000.0
	#For upgraded basins
	"Upgraded Basin Lifetime" = 28000.0

["Hammer Variables (how many ticks hammer reverts per use)"]
	#For basin
	"Basin Hammer Repair Effect" = 3200.0
	#For steam engines
	"Steam Engine Hammer Repair Effect" = 2500.0
	#For windmills, also affects time until they become unremovable
	"Windmill Hammer Repair Effect" = 1500.0
	#For water wheels, also affects time until they become unremovable
	"Waterwheel Hammer Repair Effect" = 500.0

["Spanner Variables (how many ticks spanner reverts per use)"]
	#For regular/radial/turbine engines
	"Small Engine Spanner Repair Effect" = 1500.0
	#For distillation outputs
	"Distillation Output Spanner Repair Effect" = 300.0

["Welder Toggles"]
	#self-explanatory
	"Welders Repair Basins" = true
	#self-explanatory
	"Welders Repair Steam Engines" = true

["Welder Variables (how many ticks welder reverts per use, also affects time until machines become unremovable)"]
	#For basin
	"Basin Welder Repair Effect" = 5000.0
	#For regular/radial/turbine engines
	"Small Engine Welder Repair Effect" = 5000.0
	#For large engines
	"Large Engine Welder Repair Effect" = 5000.0
	#For simple large engines
	"Small Large Engine Welder Repair Effect" = 2000.0
	#For distillation outputs
	"Distillation Output Welder Repair Effect" = 2000.0
	#For steam engines
	"Steam Engine Welder Repair Effect" = 3200.0
	#For upgraded basin
	"Upgraded Basin Welder Repair Effect" = 6500.0

[Upgrades]
	#What item, when paired with welder, upgrades basins
	"Basin Upgrade Item" = "tfmg:aluminum_block"
	#What item, when paired with welder, repairs upgraded basins
	"Upgraded Basin Repair Item" = "tfmg:aluminum_sheet"

