#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu May 07 17:02:08 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=Mellow Shader v3.1.zip
enableShaders=true
